# Generated by Django 4.2.6 on 2023-10-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdPopup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time_to_send', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetedPopup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.action')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_logged_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.user')),
            ],
        ),
        migrations.CreateModel(
            name='TargetedPopupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_text', models.TextField()),
                ('user_rating_stars', models.PositiveIntegerField()),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.targetedpopup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.user')),
            ],
        ),
        migrations.CreateModel(
            name='PopupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.group')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.adpopup')),
            ],
        ),
    ]
